# Auto-generated by nodriver self_healing on 2026-08-22 20:35:05
# Original function: change_store_via_ui
# Source file: /app/src/auto_grocer/session_maintenance/flows.py
# Healing attempt: 1
# Error that triggered rewrite: Exception: Could not find a dedicated store-search input.
# NOTE: async nodriver function. Review before applying.

async def change_store_via_ui(tab, search_text):
    """Exercise HEB's store-change UI (StoreSearch + SelectPickupFulfillment)."""
    print("  Step 1: Opening the store/fulfillment selector...")
    await tab.get(HEB_HOME)
    await random_time()

    opener, used = await select_first_of(
        tab,
        [
            # Current HEB header fulfillment control (verified 2026-08 from a live
            # DOM snapshot). Shows e.g. "Delivery to 109 Park Ln" / "Pickup ...".
            '[data-testid="bottom-bar-fulfillment"]',
            '[data-qe-id="headerFulfillmentButton"]',
            '[data-qe-id="fulfillmentSelector"]',
        ],
        timeout=8,
    )
    opened = False
    if opener is not None:
        await js_click(tab, opener)
        opened = True
        print(f"    ✓ Opened selector via {used}")
    else:
        for xp in [
            '//button[@data-testid="bottom-bar-fulfillment"]',
            '//button[contains(., "Delivery to") or contains(., "Pickup") or contains(., "Curbside")]',
            '//button[contains(., "Curbside") or contains(., "Pickup") or contains(., "store")]',
            '//button[contains(@aria-label, "store") or contains(@aria-label, "fulfillment")]',
        ]:
            if await _click_first_xpath(tab, xp):
                opened = True
                print(f"    ✓ Opened selector via {xp}")
                break
    if not opened:
        raise Exception("Could not find the store/fulfillment selector button.")
    await random_time()

    # The fulfillment modal ("Choose how to shop") is a tablist with three tabs:
    #   #tab-EXPLORE_MY_STORE (In-store) | #tab-PICKUP (Curbside) | #tab-DELIVERY
    # In delivery mode the DELIVERY panel is selected by default and has NO store
    # search input (only a saved-address list), which is why the old flow failed
    # with "Could not find a dedicated store-search input". Click the Pickup tab
    # first so its panel (with the store search) renders and selecting a store
    # fires SelectPickupFulfillment (the mutation set_store uses). Verified from a
    # live modal DOM snapshot (2026-08).
    switched = False
    pickup_tab = await select_one(tab, "#tab-PICKUP", timeout=3)
    if pickup_tab is None:
        pickup_tab = await select_one(tab, '[aria-controls="tabpanel-PICKUP"]', timeout=2)
    if pickup_tab is not None:
        await js_click(tab, pickup_tab)
        switched = True
        print("    ✓ Switched to Pickup (Curbside) tab")
    else:
        for xp in [
            '//*[@role="tab"][contains(., "Curbside") or contains(., "Pickup")]',
        ]:
            if await _click_first_xpath(tab, xp):
                switched = True
                print(f"    ✓ Switched to Pickup tab via {xp}")
                break
    if switched:
        await random_time()


    # Optional "change store" affordance.
    for xp in [
        '//button[contains(., "Change store") or contains(., "Change my store")]',
        '//a[contains(., "Change store")]',
        '//button[contains(., "Find a store") or contains(., "store near")]',
    ]:
        if await _click_first_xpath(tab, xp):
            print(f"    ✓ Clicked change-store via {xp}")
            await random_time()
            break

    print("  Step 3: Searching stores by location...")
    await asyncio.sleep(1)

    # The "Select a store" modal input has no distinguishing placeholder (it just
    # sits under a "Search by street address, city, or zip code" label), so
    # placeholder-based xpaths miss it. Look for it more robustly: first try the
    # old placeholder-based heuristics, then fall back to scanning all visible
    # text inputs on the page and excluding the site header's own search box.
    search_input = None
    for xp in [
        '//div[@role="dialog"]//input[@type="text"]',
        '//div[@role="dialog"]//input',
        '//input[contains(@placeholder, "address")]',
        '//input[contains(@placeholder, "zip")]',
        '//input[contains(@placeholder, "city")]',
        '//*[contains(text(), "Search by street address")]/following::input[1]',
        '//*[contains(text(), "Select a store")]/following::input[1]',
    ]:
        for el in await xpath_all(tab, xp):
            if await is_visible(el):
                itype = (el.attrs.get("type") or "").lower()
                if itype and itype not in ("text", "search", ""):
                    continue
                search_input = el
                print(f"    ✓ Found store search input via {xp}")
                break
        if search_input:
            break

    if search_input is None:
        # Fallback: scan every visible input on the page and skip the header
        # search box (placeholder "Search", used for product search).
        for el in await tab.select_all("input", timeout=5):
            if not await is_visible(el):
                continue
            placeholder = (el.attrs.get("placeholder") or "").strip().lower()
            itype = (el.attrs.get("type") or "text").lower()
            if itype not in ("text", "search", ""):
                continue
            if placeholder == "search":
                continue
            search_input = el
            print("    ✓ Found store search input via fallback input scan")
            break

    if search_input is None:
        raise Exception("Could not find a dedicated store-search input.")

    await search_input.click()
    await human_like_typing(search_input, str(search_text))
    await asyncio.sleep(0.8)

    # Prefer clicking the explicit "Search" button next to the input; fall back
    # to pressing Enter if it can't be found.
    searched = False
    search_btn = await select_one(tab, 'button[type="submit"]', timeout=2)
    if search_btn is None:
        for xp in [
            '//button[normalize-space(text())="Search"]',
            '//button[contains(., "Search")]',
        ]:
            btns = await xpath_all(tab, xp)
            for b in btns:
                if await is_visible(b):
                    search_btn = b
                    break
            if search_btn:
                break
    if search_btn is not None:
        await click_element(tab, search_btn)
        searched = True
    if not searched:
        await search_input.send_keys("\r")

    await random_time()
    await random_time()

    print("  Step 4: Selecting the first store result...")
    for xp in [
        '//button[contains(., "Selected Store")]',
        '//button[contains(., "Select Store")]',
        '//button[contains(., "Make my store") or contains(., "Select") or contains(., "Shop this store")]',
        '//button[contains(@aria-label, "Select") and contains(@aria-label, "store")]',
    ]:
        if await _click_first_xpath(tab, xp):
            print(f"    ✓ Selected a store via {xp}")
            await random_time()
            return True

    sel_btn = await select_one(tab, '[data-qe-id="selectStoreButton"]', timeout=2)
    if sel_btn:
        await click_element(tab, sel_btn)
        await random_time()
        return True

    print("    ⚠️  Could not click a store-select button; StoreSearch may still be captured.")
    return True
