# Auto-generated by nodriver self_healing on 2026-09-23 02:59:26
# Original function: change_store_via_ui
# Source file: /app/src/auto_grocer/session_maintenance/flows.py
# Healing attempt: 1
# Error that triggered rewrite: Exception: Could not find a dedicated store-search input.
# NOTE: async nodriver function. Review before applying.

async def change_store_via_ui(tab, search_text):
    """Exercise HEB's store-change UI (StoreSearch + SelectPickupFulfillment)."""
    print("  Step 1: Opening the store/fulfillment selector...")
    await tab.get(HEB_HOME)
    await random_time()

    opener, used = await select_first_of(
        tab,
        [
            # Current HEB header fulfillment control (verified 2026-08 from a live
            # DOM snapshot). Shows e.g. "Delivery to 109 Park Ln" / "Pickup ...".
            '[data-testid="bottom-bar-fulfillment"]',
            '[data-qe-id="headerFulfillmentButton"]',
            '[data-qe-id="fulfillmentSelector"]',
        ],
        timeout=8,
    )
    opened = False
    if opener is not None:
        await js_click(tab, opener)
        opened = True
        print(f"    ✓ Opened selector via {used}")
    else:
        for xp in [
            '//button[@data-testid="bottom-bar-fulfillment"]',
            '//button[contains(., "Delivery to") or contains(., "Pickup") or contains(., "Curbside")]',
            '//button[contains(., "Curbside") or contains(., "Pickup") or contains(., "store")]',
            '//button[contains(@aria-label, "store") or contains(@aria-label, "fulfillment")]',
        ]:
            if await _click_first_xpath(tab, xp):
                opened = True
                print(f"    ✓ Opened selector via {xp}")
                break
    if not opened:
        raise Exception("Could not find the store/fulfillment selector button.")
    await random_time()

    # The fulfillment modal ("Choose how to shop") is a tablist with three tabs:
    #   #tab-EXPLORE_MY_STORE (In-store) | #tab-PICKUP (Curbside) | #tab-DELIVERY
    # In delivery mode the DELIVERY panel is selected by default and has NO store
    # search input (only a saved-address list). Click the Pickup tab first so its
    # panel (with the store search) renders. If Curbside/Pickup is already the
    # active tab (as it commonly is for pickup carts), this click is a harmless
    # no-op. Verified from a live modal DOM snapshot (2026-08).
    switched = False
    pickup_tab = await select_one(tab, "#tab-PICKUP", timeout=3)
    if pickup_tab is None:
        pickup_tab = await select_one(tab, '[aria-controls="tabpanel-PICKUP"]', timeout=2)
    if pickup_tab is not None:
        await js_click(tab, pickup_tab)
        switched = True
        print("    ✓ Switched to Pickup (Curbside) tab")
    else:
        for xp in [
            '//*[@role="tab"][contains(., "Curbside") or contains(., "Pickup")]',
        ]:
            if await _click_first_xpath(tab, xp):
                switched = True
                print(f"    ✓ Switched to Pickup tab via {xp}")
                break
    if switched:
        await random_time()

    # Optional "change store" affordance. On the Curbside panel this shows the
    # currently-selected store (e.g. "East Hopkins H-E-B") with a "Change store"
    # link next to it (verified 2026-08 screenshot). It is not always a
    # <button>/<a> tag, so search across any element and fall back to a fuzzy
    # text search via tab.find().
    clicked_change = False
    for xp in [
        '//button[contains(., "Change store") or contains(., "Change my store")]',
        '//a[contains(., "Change store")]',
        '//*[self::button or self::a or self::span or self::div]'
        '[contains(., "Change store") and not(.//*[contains(., "Change store")])]',
        '//button[contains(., "Find a store") or contains(., "store near")]',
    ]:
        if await _click_first_xpath(tab, xp):
            print(f"    ✓ Clicked change-store via {xp}")
            clicked_change = True
            await random_time()
            break

    if not clicked_change:
        try:
            change_el = await tab.find("Change store", best_match=True)
        except Exception:
            change_el = None
        if change_el is not None:
            try:
                await change_el.scroll_into_view()
            except Exception:
                pass
            await js_click(tab, change_el)
            clicked_change = True
            print("    ✓ Clicked change-store via tab.find()")
            await random_time()

    print("  Step 3: Searching stores by location...")
    await asyncio.sleep(1)
    search_input = None
    for xp in [
        '//div[@role="dialog"]//input[@type="text"]',
        '//div[@role="dialog"]//input[@placeholder]',
        '//input[contains(@placeholder, "address")]',
        '//input[contains(@placeholder, "zip")]',
        '//input[contains(@placeholder, "city")]',
        '//input[contains(@placeholder, "Zip") or contains(@placeholder, "City")]',
        '//input[contains(@placeholder, "store")]',
        '//input[contains(@placeholder, "Store")]',
        '//input[contains(@aria-label, "address") or contains(@aria-label, "zip") or contains(@aria-label, "city") or contains(@aria-label, "store")]',
        '//input[@type="text" or @type="search"]',
    ]:
        for el in await xpath_all(tab, xp):
            if await is_visible(el):
                search_input = el
                print(f"    ✓ Found store search input via {xp}")
                break
        if search_input:
            break

    if search_input is None:
        # Last resort: any visible text/search input on the page.
        for el in await tab.select_all('input', timeout=3):
            try:
                el_type = (el.attrs.get('type') or '').lower()
            except Exception:
                el_type = ''
            if el_type in ('text', 'search', '') and await is_visible(el):
                search_input = el
                print("    ✓ Found store search input via generic <input> fallback")
                break

    if search_input is None:
        raise Exception("Could not find a dedicated store-search input.")

    await human_like_typing(search_input, str(search_text))
    await asyncio.sleep(0.8)
    await search_input.send_keys("\r")
    await random_time()
    await random_time()

    print("  Step 4: Selecting the first store result...")
    for xp in [
        '//button[contains(., "Selected Store")]',
        '//button[contains(., "Select Store")]',
        '//button[contains(., "Make my store") or contains(., "Select") or contains(., "Shop this store")]',
        '//button[contains(@aria-label, "Select") and contains(@aria-label, "store")]',
    ]:
        if await _click_first_xpath(tab, xp):
            print(f"    ✓ Selected a store via {xp}")
            await random_time()
            return True

    sel_btn = await select_one(tab, '[data-qe-id="selectStoreButton"]', timeout=2)
    if sel_btn:
        await click_element(tab, sel_btn)
        await random_time()
        return True

    print("    ⚠️  Could not click a store-select button; StoreSearch may still be captured.")
    return True
