# Auto-generated by nodriver self_healing on 2026-08-26 01:38:59
# Original function: change_store_via_ui
# Source file: /app/src/auto_grocer/session_maintenance/flows.py
# Healing attempt: 3
# Error that triggered rewrite: Exception: Could not find a dedicated store-search input.
# NOTE: async nodriver function. Review before applying.


