# Auto-generated by nodriver self_healing on 2026-08-22 02:52:42
# Original function: reserve_time_slot
# Source file: /app/src/auto_grocer/session_maintenance/flows.py
# Healing attempt: 1
# Error that triggered rewrite: Exception: No timeslots found or could not select. Found 0 elements.
# NOTE: async nodriver function. Review before applying.

async def reserve_time_slot(tab):
    """Reserve a curbside pickup time slot (async, handles the tiered modal)."""
    # STEP 1: ensure on cart
    print("  Step 1: Navigating to cart...")
    if "/cart" not in await _current_url(tab):
        await tab.get(HEB_CART)
        await random_time()

    if await check_exists_by_xpath(tab, '//*[contains(text(), "Change time")]'):
        print("  ✓ Time slot already reserved")
        return True

    # STEP 2: let blocking modals settle
    print("  Step 2: Waiting for any blocking modals to clear...")
    await asyncio.sleep(1)

    # STEP 3: open the reservation modal
    print("  Step 3: Opening reservation modal...")
    reserve_button, _ = await select_first_of(
        tab,
        [
            'button[data-qe-id="chooseReservationTime"]',
            'button[aria-label*="Choose reservation time"]',
        ],
        timeout=10,
    )
    if reserve_button is not None:
        await scroll_to_element(reserve_button)
        await click_element(tab, reserve_button)
        print("    ✓ Clicked 'Choose pickup time' button")
    elif await _click_first_xpath(
        tab,
        '//button[contains(., "Choose pickup time") or contains(., "Choose a time") '
        'or contains(@aria-label, "Choose")]',
    ):
        print("    ✓ Clicked 'Choose pickup time' button (fallback)")
    else:
        raise Exception("Could not find 'Choose pickup time' button")
    await random_time()
    await asyncio.sleep(3)

    # STEP 4: ensure Curbside tab is selected
    print("  Step 4: Ensuring Curbside tab is selected...")
    for tab_el in await xpath_all(
        tab, '//button[contains(text(), "Curbside")] | //*[@role="tab" and contains(text(), "Curbside")]'
    ):
        try:
            if attr(tab_el, "aria-selected") != "true":
                await click_element(tab, tab_el)
                await random_time()
                print("    ✓ Selected Curbside tab")
            else:
                print("    ✓ Curbside tab already selected")
        except Exception:  # noqa: BLE001
            pass
        break
    await asyncio.sleep(2)

    # STEP 4.5: select a delivery tier (refreshed tiered timeslot UI).
    print("  Step 4.5: Selecting a delivery tier...")
    tier_buttons = await select_all(tab, 'button[class*="TimeslotSummary_button"]', timeout=3)
    if not tier_buttons:
        tier_buttons = await xpath_all(tab, '//button[contains(@aria-label, "time slots for")]')

    visible_tiers = []
    for b in tier_buttons:
        if await is_visible(b):
            visible_tiers.append(b)

    if not visible_tiers:
        print("    ℹ️  No tier buttons found; assuming legacy date-grid layout.")
    else:
        preferred = None
        for b in visible_tiers:
            label = attr(b, "aria-label", "") or ""
            if "Scheduled" in label or "for Free" in label:
                preferred = b
                break
        target = preferred or visible_tiers[-1]
        label = (attr(target, "aria-label", "tier") or "tier").strip()
        await scroll_to_element(target)
        await click_element(tab, target)
        print(f"    ✓ Selected delivery tier: {label[:60]}")
        await random_time()
        await asyncio.sleep(2)

    # Helper to look
