"""Async, nodriver-aware self-healing.

Same idea as utility/self_healing.py: on a runtime error, send the broken
function's source + traceback + page HTML + a screenshot to Claude, ask for a
corrected version, compile it, save it to grocery_browser/updated_functions/,
and retry. The difference: the functions here are ``async def`` and use the
nodriver tab API, so the repaired function must also be async and is awaited.
"""
from __future__ import annotations

import os
import re
import asyncio
import inspect
import textwrap
import traceback
import datetime

from claude import client, MODEL


UPDATED_FUNCTIONS_DIR = os.path.join(os.path.dirname(__file__), "updated_functions")


# A short cheatsheet so Claude rewrites against the right async API.
_NODRIVER_API_NOTES = (
    "This code uses the `nodriver` async browser API (NOT Selenium). Conventions:\n"
    "  * The function is `async def` and you MUST `await` all browser calls.\n"
    "  * `tab` is a nodriver Tab. Navigation: `await tab.get(url)`.\n"
    "  * Find one element: `await tab.select(css, timeout=10)` (raises on miss).\n"
    "  * Find many: `await tab.select_all(css, timeout=5)`.\n"
    "  * XPath: `await tab.xpath(xpath, timeout=2.5)` -> list.\n"
    "  * Text search: `await tab.find('some text', best_match=True)`.\n"
    "  * Element: `await el.click()`, `await el.send_keys(text)`, "
    "`await el.scroll_into_view()`, `await el.apply('(e)=>e.click()')`.\n"
    "  * Attributes: use `el.attrs.get('aria-label')` (there is NO get_attribute).\n"
    "  * Run JS on the page: `await tab.evaluate('document.title')`.\n"
    "  * Sleeps: `await asyncio.sleep(seconds)`.\n"
    "  * Helpers from grocery_browser.primitives may be referenced if already "
    "imported in the original (random_time, select_one, select_all, click_element, "
    "attr, is_visible, dismiss_modals, check_exists_by_xpath).\n"
)


def _ensure_output_dir():
    os.makedirs(UPDATED_FUNCTIONS_DIR, exist_ok=True)


def _save_updated_function(func_name, new_code, source_file, attempt, error_msg):
    _ensure_output_dir()
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = (
        f"# Auto-generated by nodriver self_healing on {timestamp}\n"
        f"# Original function: {func_name}\n"
        f"# Source file: {source_file}\n"
        f"# Healing attempt: {attempt}\n"
        f"# Error that triggered rewrite: {error_msg}\n"
        f"# NOTE: async nodriver function. Review before applying.\n\n"
    )
    filepath = os.path.join(UPDATED_FUNCTIONS_DIR, f"{func_name}.py")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(new_code)
        f.write("\n")
    print(f"    💾 Saved rewritten function to: grocery_browser/updated_functions/{func_name}.py")
    return filepath


def _extract_function_code(response_text):
    cleaned = re.sub(r"^```(?:python)?\s*\n", "", response_text.strip())
    cleaned = re.sub(r"\n```\s*$", "", cleaned)
    return cleaned.strip()


def _build_heal_prompt(func_name, source, error, tb_str, html_context=None):
    prompt = (
        f"The following async Python function raised an error at runtime.\n\n"
        f"{_NODRIVER_API_NOTES}\n"
        f"Function name: {func_name}\n"
        f"Error type: {type(error).__name__}\n"
        f"Error message: {error}\n\n"
        f"Traceback:\n{tb_str}\n\n"
        f"Current function source:\n```python\n{source}\n```\n\n"
    )
    if html_context:
        max_html = 50000
        if len(html_context) > max_html:
            html_context = html_context[:max_html] + "\n... (truncated)"
        prompt += (
            "Here is the HTML of the page at the time of the error "
            "(use this to find correct selectors):\n"
            f"```html\n{html_context}\n```\n\n"
        )
    prompt += (
        "A screenshot of the browser at the time of the error is attached. "
        "Use it to understand what is visible.\n\n"
        "Rewrite ONLY this function to fix the error. Keep the SAME async "
        "signature and name. It MUST remain `async def` and await all browser "
        "calls. Return ONLY the corrected Python function code with no markdown "
        "fences, no explanation, and no imports (assume original imports exist)."
    )
    return prompt


def _build_message_content(prompt_text, screenshot_b64=None):
    content = []
    if screenshot_b64:
        content.append({
            "type": "image",
            "source": {
                "type": "base64",
                "media_type": "image/png",
                "data": screenshot_b64,
            },
        })
    content.append({"type": "text", "text": prompt_text})
    return content


async def self_healing_call(
    func, *args, max_retries=3, tab=None, logger=None, html_context=None, **kwargs
):
    """Call an async function with Claude-powered auto-repair on failure.

    Args:
        func: The async function to call.
        *args: Positional args for func.
        max_retries: Max heal-and-retry attempts.
        tab: nodriver Tab, used to grab a screenshot + HTML on error.
        logger: AsyncDriverLogger for screenshot capture (optional).
        html_context: Optional page HTML override.
        **kwargs: Keyword args for func.

    Returns:
        The function's return value on success.

    Raises:
        The last exception if all retries are exhausted.
    """
    if client is None:
        raise RuntimeError(
            "Claude API client not initialized. Cannot self-heal without an API key."
        )

    source = textwrap.dedent(inspect.getsource(func))
    source_file = inspect.getfile(func)
    current_func = func

    for attempt in range(max_retries + 1):
        try:
            return await current_func(*args, **kwargs)
        except Exception as e:
            tb_str = traceback.format_exc()

            if "Connection refused" in str(e) or "NewConnectionError" in str(e):
                print(f"\n    ❌ {func.__name__}: Browser connection lost. Skipping retries.")
                raise

            if attempt == max_retries:
                print(
                    f"\n    ❌ self_healing: {func.__name__} failed after "
                    f"{max_retries} heal attempts. Raising original error."
                )
                raise

            print(f"\n    🔧 self_healing: {func.__name__} raised {type(e).__name__}: {e}")
            print(f"    🤖 Asking Claude to rewrite (attempt {attempt + 1}/{max_retries})...")

            screenshot_b64 = None
            current_html = html_context
            if tab is not None:
                print("    📸 Capturing screenshot for Claude...")
                if logger is not None:
                    screenshot_b64 = await logger.screenshot_b64(tab)
                else:
                    try:
                        screenshot_b64 = await tab.save_screenshot(format="png", as_base64=True)
                    except Exception:  # noqa: BLE001
                        screenshot_b64 = None
                if not current_html:
                    try:
                        current_html = await tab.get_content()
                    except Exception:  # noqa: BLE001
                        pass

            prompt = _build_heal_prompt(func.__name__, source, e, tb_str, current_html)
            message_content = _build_message_content(prompt, screenshot_b64)

            # The Anthropic client is sync; run it off the event loop.
            def _call_claude():
                return client.messages.create(
                    model=MODEL,
                    max_tokens=4096,
                    messages=[{"role": "user", "content": message_content}],
                )

            response = await asyncio.to_thread(_call_claude)
            new_code = _extract_function_code(response.content[0].text)

            namespace = {**func.__globals__}
            try:
                exec(new_code, namespace)
            except SyntaxError as se:
                print(f"    ⚠️  Claude returned code with syntax error: {se}")
                continue

            if func.__name__ not in namespace:
                print(f"    ⚠️  Claude's response did not define {func.__name__}. Retrying...")
                continue

            candidate = namespace[func.__name__]
            if not inspect.iscoroutinefunction(candidate):
                print("    ⚠️  Claude returned a non-async function; ignoring this rewrite.")
                continue

            current_func = candidate
            source = new_code
            _save_updated_function(
                func.__name__, new_code, source_file, attempt + 1, f"{type(e).__name__}: {e}"
            )
            print(f"    ⟳ Retrying with rewritten {func.__name__}...")
