# Auto-generated by self_healing on 2026-06-19 00:20:41
# Original function: change_store_via_ui
# Source file: /mnt/c/Users/benbo/OneDrive/Desktop/Development/GitHub/Python/auto_grocier/main.py
# Healing attempt: 1
# Error that triggered rewrite: Exception: Could not find a dedicated store-search input. The store/fulfillment modal may not have opened (refusing to type into the global product-search box).
#
# Review this code before applying with apply_updates.py

def change_store_via_ui(driver, search_text):
    """Drive HEB's store-change UI to trigger StoreSearch + SelectPickupFulfillment.

    This is used by the ``update_graphql_hashes`` capture mode so the GraphQL
    requests for store search and store change appear in the browser's network
    log (and their persisted-query hashes can be captured). It does NOT need to
    permanently change the store — it only needs to exercise those two requests.

    Args:
        driver: Selenium WebDriver instance.
        search_text: A zip code or city/state to search stores by.

    Returns:
        True if the store search/selection UI was exercised.
    """
    wait = WebDriverWait(driver, 15)

    # STEP 1: Open the fulfillment / store selector from the header.
    print("  Step 1: Opening the store/fulfillment selector...")
    driver.get("https://www.heb.com/")
    random_time()

    opener_selectors = [
        (By.CSS_SELECTOR, '[data-qe-id="headerFulfillmentButton"]'),
        (By.CSS_SELECTOR, '[data-qe-id="fulfillmentSelector"]'),
        (By.XPATH, '//button[contains(., "Curbside") or contains(., "Pickup") or contains(., "store")]'),
        (By.XPATH, '//button[contains(@aria-label, "store") or contains(@aria-label, "fulfillment")]'),
    ]
    opened = False
    for by, sel in opener_selectors:
        try:
            btn = wait.until(EC.element_to_be_clickable((by, sel)))
            driver.execute_script("arguments[0].click();", btn)
            opened = True
            print(f"    ✓ Opened selector via {sel}")
            break
        except Exception:
            continue
    if not opened:
        raise Exception(
            "Could not find the store/fulfillment selector button. "
            "The header layout may have changed."
        )
    random_time()

    # STEP 2: Find a "change store" affordance if present.
    change_selectors = [
        (By.XPATH, '//button[contains(., "Change store") or contains(., "Change my store")]'),
        (By.XPATH, '//a[contains(., "Change store")]'),
        (By.XPATH, '//button[contains(., "Find a store") or contains(., "store near")]'),
    ]
    for by, sel in change_selectors:
        try:
            el = driver.find_element(by, sel)
            driver.execute_script("arguments[0].click();", el)
            print(f"    ✓ Clicked change-store via {sel}")
            random_time()
            break
        except Exception:
            continue

    # STEP 3: Type the search text into the store search input (fires StoreSearch).
    print("  Step 3: Searching stores by location...")
    
    # The modal is open with a visible search input
    # Based on the HTML, look for input fields within the dialog
    search_input = None
    
    # Try to find the search input within the modal dialog
    try:
        # Wait for the modal to be present
        time.sleep(1)
        
        # Try various selectors for the store search input
        input_selectors = [
            '//div[@role="dialog"]//input[@type="text"]',
            '//div[@role="dialog"]//input[@placeholder]',
            '//input[contains(@placeholder, "address")]',
            '//input[contains(@placeholder, "zip")]',
            '//input[contains(@placeholder, "city")]',
        ]
        
        for sel in input_selectors:
            try:
                search_input = wait.until(EC.presence_of_element_located((By.XPATH, sel)))
                if search_input.is_displayed():
                    print(f"    ✓ Found store search input via {sel}")
                    break
                else:
                    search_input = None
            except Exception:
                continue
                
    except Exception:
        pass

    if search_input is None:
        raise Exception(
            "Could not find a dedicated store-search input. The store/"
            "fulfillment modal may not have opened (refusing to type into the "
            "global product-search box)."
        )

    search_input.clear()
    human_like_typing(search_input, str(search_text))
    time.sleep(random.uniform(0.5, 1.0))
    search_input.send_keys(Keys.ENTER)
    random_time()
    random_time()

    # STEP 4: Select the first store result (fires SelectPickupFulfillment).
    print("  Step 4: Selecting the first store result...")
    select_selectors = [
        (By.XPATH, '//button[contains(., "Selected Store")]'),
        (By.XPATH, '//button[contains(., "Select Store")]'),
        (By.XPATH, '//button[contains(., "Make my store") or contains(., "Select") or contains(., "Shop this store")]'),
        (By.CSS_SELECTOR, '[data-qe-id="selectStoreButton"]'),
        (By.XPATH, '//button[contains(@aria-label, "Select") and contains(@aria-label, "store")]'),
    ]
    for by, sel in select_selectors:
        try:
            el = wait.until(EC.element_to_be_clickable((by, sel)))
            driver.execute_script("arguments[0].click();", el)
            print(f"    ✓ Selected a store via {sel}")
            random_time()
            return True
        except Exception:
            continue

    # Even if final selection failed, StoreSearch likely fired.
    print("    ⚠️  Could not click a store-select button; StoreSearch may still be captured.")
    return True
