# Auto-generated by self_healing on 2026-06-07 13:54:33
# Original function: clear_cart
# Source file: /mnt/c/Users/benbo/OneDrive/Desktop/Development/GitHub/Python/auto_grocier/main.py
# Healing attempt: 2
# Error that triggered rewrite: TimeoutException: Message: 

#
# Review this code before applying with apply_updates.py

def clear_cart(driver):
    """Clear all items from the HEB shopping cart"""
    try:
        # First, close any modal that might be intercepting clicks
        try:
            close_button = driver.find_element(By.CSS_SELECTOR, "button[aria-label='close']")
            if close_button.is_displayed():
                close_button.click()
                random_time()
        except:
            pass
        
        # Look for the "Empty cart" button directly on the cart page
        from selenium.webdriver.support.wait import WebDriverWait
        from selenium.webdriver.support import expected_conditions as EC
        wait = WebDriverWait(driver, 10)
        
        try:
            # Wait for and click the empty cart button using the visible text
            empty_cart_button = wait.until(EC.element_to_be_clickable((By.XPATH, "//button[contains(text(), 'Empty cart')]")))
            empty_cart_button.click()
            random_time()
            
            # Confirm the empty cart action
            confirm_empty = wait.until(EC.element_to_be_clickable((By.XPATH, "//button[contains(text(), 'Empty')]")))
            confirm_empty.click()
            random_time()
            
            # Navigate back to home
            home_link = driver.find_element(By.CSS_SELECTOR, "a[href='/']")
            home_link.click()
            random_time()
            
        except Exception as e:
            # If we can't find empty cart button, the cart might already be empty
            return 0
            
    except Exception as e:
        logger.log_failure(
            driver=driver,
            function_name="clear_cart",
            error=e,
            additional_info={"step": "clearing cart"}
        )
        raise
