# Auto-generated by self_healing on 2026-06-19 00:17:06
# Original function: reserve_time_slot
# Source file: /mnt/c/Users/benbo/OneDrive/Desktop/Development/GitHub/Python/auto_grocier/main.py
# Healing attempt: 3
# Error that triggered rewrite: Exception: Could not find 'Choose pickup time' button
#
# Review this code before applying with apply_updates.py

def reserve_time_slot(driver):
    """Reserve a curbside pickup time slot on HEB website.
    
    Updated to handle the modal-based date/time selection interface.
    The modal appears when clicking "Choose pickup time" button.
    """
    try:
        wait = WebDriverWait(driver, 15)

        # STEP 1: Navigate to cart if not already there
        print("  Step 1: Navigating to cart...")
        if "/cart" not in driver.current_url:
            driver.get("https://www.heb.com/cart/")
            random_time()

        # Check if time is already reserved
        if check_exists_by_xpath("//*[contains(text(), 'Change time')]", driver):
            print("  ✓ Time slot already reserved")
            return True

        # STEP 2: Wait for modal to be gone if it's blocking
        print("  Step 2: Waiting for any blocking modals to clear...")
        try:
            # Wait for modal cover to disappear if present
            WebDriverWait(driver, 10).until(
                EC.invisibility_of_element_located((By.CSS_SELECTOR, '.ModalContainers_modalCover__1tKfw, [data-component="modal-cover-container"]'))
            )
            time.sleep(1)
        except:
            # Modal cover not present or already gone
            pass

        # STEP 3: Click the 'Choose pickup time' button from the cart page
        print("  Step 3: Opening reservation modal...")
        try:
            # Wait for button to be clickable and not obscured
            reserve_button = wait.until(EC.element_to_be_clickable(
                (By.CSS_SELECTOR, 'button[data-qe-id="chooseReservationTime"], button[aria-label*="Choose reservation time"]')
            ))
            
            # Scroll button into view
            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", reserve_button)
            time.sleep(1)
            
            # Try to click
            try:
                reserve_button.click()
            except:
                # Use JavaScript click if regular click fails
                driver.execute_script("arguments[0].click();", reserve_button)
            
            print("    ✓ Clicked 'Choose pickup time' button")
        except:
            # Try alternative selectors
            try:
                reserve_button = wait.until(EC.element_to_be_clickable(
                    (By.XPATH, '//button[contains(., "Choose pickup time") or contains(., "Choose a time") or contains(@aria-label, "Choose")]')
                ))
                driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", reserve_button)
                time.sleep(1)
                driver.execute_script("arguments[0].click();", reserve_button)
                print("    ✓ Clicked 'Choose pickup time' button (fallback)")
            except:
                raise Exception("Could not find 'Choose pickup time' button")

        random_time()
        time.sleep(3)  # Wait for modal to fully load

        # STEP 4: Ensure Curbside tab is selected
        print("  Step 4: Ensuring Curbside tab is selected...")
        try:
            curbside_tabs = driver.find_elements(By.XPATH, '//button[contains(text(), "Curbside")] | //*[@role="tab" and contains(text(), "Curbside")]')
            for tab in curbside_tabs:
                if tab.get_attribute("aria-selected") != "true":
                    tab.click()
                    random_time()
                    print("    ✓ Selected Curbside tab")
                else:
                    print("    ✓ Curbside tab already selected")
                break
        except Exception as e:
            print(f"    ⚠️  Could not check Curbside tab: {e}")

        time.sleep(2)

        # STEP 5: Select a date
        print("  Step 5: Selecting a date...")
        date_buttons = []
        
        # Try different possible selectors
        selectors = [
            'button[id^="date-button-"]',
            'input[type="radio"][name*="date"]',
            'button[aria-label*="date"]',
            'label[for^="date-button-"]',
            '[role="button"][id*="date"]',
        ]
        
        for selector in selectors:
            date_buttons = driver.find_elements(By.CSS_SELECTOR, selector)
            if date_buttons:
                print(f"    Found {len(date_buttons)} date options using selector: {selector}")
                break
        
        if not date_buttons:
            # Fallback: look for any clickable elements in the modal that might be dates
            date_buttons = driver.find_elements(By.XPATH, 
                '//button[contains(@class, "date") or contains(@class, "Date")] | '
                '//div[contains(@class, "date") or contains(@class, "Date")]//button'
            )
            if date_buttons:
                print(f"    Found {len(date_buttons)} date options using fallback xpath")

        date_selected = False
        for btn in date_buttons:
            try:
                if not btn.is_displayed() or not btn.is_enabled():
                    continue
                
                text_content = btn.get_attribute('textContent') or btn.get_attribute('innerText') or ''
                aria_label = btn.get_attribute('aria-label') or ''
                
                if 'Free' in text_content or 'Free' in aria_label or btn.get_attribute('aria-disabled') != 'true':
                    try:
                        btn.click()
                    except:
                        driver.execute_script("arguments[0].click();", btn)
                    
                    print(f"    📅 Selected date: {text_content.strip()[:50] if text_content else aria_label[:50]}")
                    date_selected = True
                    random_time()
                    break
            except Exception as e:
                continue

        if not date_selected and date_buttons:
            try:
                date_buttons[0].click()
                print("    📅 Selected first available date")
                date_selected = True
                random_time()
            except:
                try:
                    driver.execute_script("arguments[0].click();", date_buttons[0])
                    print("    📅 Selected first available date (via JS)")
                    date_selected = True
                    random_time()
                except:
                    pass

        if not date_selected:
            raise Exception(
                f"No dates found or could not select date. Tried multiple selectors, found {len(date_buttons)} elements."
            )

        time.sleep(2)

        # STEP 6: Select a timeslot
        print("  Step 6: Selecting a timeslot...")
        timeslot_elements = []
        
        timeslot_selectors = [
            'input[type="radio"][data-qe-id="timeslotRadioButton"]',
            'input[type="radio"][name*="timeslot"]',
            'input[type="radio"][name*="time"]',
            'button[data-qe-id*="timeslot"]',
            '[role="radio"][aria-label*="time"]',
        ]
        
        for selector in timeslot_selectors:
            timeslot_elements = driver.find_elements(By.CSS_SELECTOR, selector)
            if timeslot_elements:
                print(f"    Found {len(timeslot_elements)} timeslot options using selector: {selector}")
                break
        
        if not timeslot_elements:
            timeslot_elements = driver.find_elements(By.XPATH,
                '//input[@type="radio"] | '
                '//button[contains(@class, "time") or contains(@class, "Time")] | '
                '//div[contains(@class, "timeslot")]//input[@type="radio"]'
            )
            if timeslot_elements:
                print(f"    Found {len(timeslot_elements)} timeslot options using fallback xpath")

        timeslot_selected = False
        for slot in timeslot_elements:
            try:
                disabled = slot.get_attribute('disabled') or slot.get_attribute('aria-disabled') == 'true'
                if disabled:
                    continue

                try:
                    driver.execute_script("arguments[0].click();", slot)
                except:
                    slot.click()
                
                aria_label = slot.get_attribute('aria-label') or ''
                slot_desc = aria_label[:60] if aria_label else "timeslot"
                print(f"    🕐 Selected timeslot: {slot_desc}")
                timeslot_selected = True
                break
            except Exception as e:
                continue

        if not timeslot_selected:
            raise Exception(
                f"No timeslots found or could not select. Found {len(timeslot_elements)} elements."
            )

        # STEP 7: Wait for selection to register
        print("  Step 7: Waiting for timeslot selection to register...")
        time.sleep(3)

        # Try to close the modal if it's still open
        try:
            close_btns = driver.find_elements(By.CSS_SELECTOR, 
                '[aria-label="close"], [aria-label="Close"], button[class*="close"], button[class*="Close"]'
            )
            for btn in close_btns:
                try:
                    if btn.is_displayed():
                        btn.click()
                        print("    ✓ Closed modal")
                        break
                except:
                    continue
        except:
            pass

        time.sleep(2)

        # Verify reservation
        if check_exists_by_xpath("//*[contains(text(), 'Change time')]", driver):
            print("  ✓ Time slot successfully reserved!")
        else:
            print("  ✓ Time slot reservation process completed (could not verify)")

        return True

    except Exception as e:
        logger.log_failure(
            driver=driver,
            function_name="reserve_time_slot",
            error=e,
            additional_info={
                "step": "reserving time slot",
                "url": driver.current_url
            }
        )
        # Try to close modal on failure
        try:
            close_buttons = driver.find_elements(By.CSS_SELECTOR, '[aria-label="close"], [aria-label="Close"]')
            for btn in close_buttons:
                try:
                    btn.click()
                    break
                except:
                    continue
        except:
            pass
        raise
