# Auto-generated by self_healing on 2026-06-07 18:42:20
# Original function: reserve_time_slot
# Source file: /mnt/c/Users/benbo/OneDrive/Desktop/Development/GitHub/Python/auto_grocier/main.py
# Healing attempt: 2
# Error that triggered rewrite: Exception: No free dates found. Found 8 date elements but none were selectable. The page layout may have changed.
#
# Review this code before applying with apply_updates.py

def reserve_time_slot(driver):
    """Reserve a curbside pickup time slot on HEB website.

    Flow:
    1. Navigate to cart page
    2. Click 'Choose a time' button to open reservation modal
    3. Ensure 'Curbside' tab is selected
    4. Pick the first available (Free, non-Full) date
    5. Pick the first available free timeslot
    6. Click 'Select this time' to confirm
    """
    try:
        wait = WebDriverWait(driver, 15)

        # STEP 1: Navigate to cart if not already there
        print("  Step 1: Navigating to cart...")
        if "/cart" not in driver.current_url:
            driver.get("https://www.heb.com/cart/")
            random_time()

        # Check if time is already reserved
        if check_exists_by_xpath("//*[contains(text(), 'Change time')]", driver):
            print("  ✓ Time slot already reserved")
            return True

        # STEP 2: Click the 'Choose pickup time' button from the cart page
        print("  Step 2: Opening reservation modal...")
        try:
            # Look for the specific button with icon and text "Choose pickup time"
            reserve_button = wait.until(EC.element_to_be_clickable(
                (By.XPATH, '//button[contains(., "Choose pickup time") or .//span[contains(text(), "Choose pickup time")]]')
            ))
            reserve_button.click()
            print("    ✓ Clicked 'Choose pickup time' button")
        except:
            try:
                # Fallback: look for button in the curbside fulfillment section
                reserve_button = wait.until(EC.element_to_be_clickable(
                    (By.XPATH, '//button[contains(@aria-label, "Choose pickup time") or contains(@aria-label, "pickup time")]')
                ))
                reserve_button.click()
                print("    ✓ Clicked pickup time button")
            except:
                raise Exception("Could not find pickup time selection button")
        
        random_time()

        # STEP 3: Make sure the Curbside tab is selected
        print("  Step 3: Ensuring Curbside tab is selected...")
        try:
            # Look for curbside tab or pickup option
            curbside_elements = driver.find_elements(By.XPATH, '//*[contains(text(), "Curbside") or contains(text(), "CURBSIDE") or contains(@id, "CURBSIDE")]')
            for element in curbside_elements:
                if element.tag_name in ['button', 'a'] or element.get_attribute('role') == 'tab':
                    if element.get_attribute("aria-selected") != "true":
                        element.click()
                        random_time()
                        print("    ✓ Selected Curbside option")
                    else:
                        print("    ✓ Curbside already selected")
                    break
        except Exception as e:
            print(f"    ⚠️  Could not check/click Curbside tab: {e}")

        # Wait for modal/page to load
        time.sleep(3)
        
        # STEP 4: Select a free date
        print("  Step 4: Selecting a free date...")
        
        # Look for date selection elements with various approaches
        date_elements = []
        
        # Try to find radio buttons for dates
        date_radios = driver.find_elements(By.XPATH, '//input[@type="radio" and (contains(@name, "date") or contains(@aria-label, "date") or contains(@value, "2025"))]')
        if date_radios:
            print(f"    Found {len(date_radios)} date radio buttons")
            date_elements = date_radios
        
        # Try to find clickable date buttons or labels
        if not date_elements:
            date_buttons = driver.find_elements(By.XPATH, '//button[contains(@aria-label, "date") or contains(text(), "Jan") or contains(text(), "Feb") or contains(text(), "Mar") or contains(text(), "Apr") or contains(text(), "May") or contains(text(), "Jun") or contains(text(), "Jul") or contains(text(), "Aug") or contains(text(), "Sep") or contains(text(), "Oct") or contains(text(), "Nov") or contains(text(), "Dec")]')
            if date_buttons:
                print(f"    Found {len(date_buttons)} date buttons")
                date_elements = date_buttons
        
        # Try to find any elements with date-related data attributes
        if not date_elements:
            date_elements = driver.find_elements(By.CSS_SELECTOR, '[data-testid*="date"], [data-qe-id*="date"], [aria-label*="date"], [class*="date"]')
            if date_elements:
                print(f"    Found {len(date_elements)} date-related elements")

        date_selected = False
        for element in date_elements:
            try:
                # Get text content and attributes to check availability
                element_text = element.get_attribute('textContent') or element.text or ''
                aria_label = element.get_attribute('aria-label') or ''
                value = element.get_attribute('value') or ''
                combined_text = f"{element_text} {aria_label} {value}".lower()
                
                # Skip if element is disabled or marked as full
                if element.get_attribute('disabled') or 'full' in combined_text or 'unavailable' in combined_text:
                    print(f"    ⏭️  Skipping (unavailable): {element_text or aria_label}")
                    continue
                
                # Check if it's already selected
                if element.get_attribute('checked') == 'true' or element.get_attribute('aria-checked') == 'true' or 'selected' in element.get_attribute('class') or '':
                    print(f"    ✓ Date already selected: {element_text or aria_label}")
                    date_selected = True
                    break
                
                # Try to click the element
                try:
                    if element.tag_name == 'input':
                        # For radio inputs, click directly
                        driver.execute_script("arguments[0].click();", element)
                    else:
                        # For buttons or other clickable elements
                        element.click()
                    
                    print(f"    📅 Selected date: {element_text or aria_label}")
                    random_time()
                    date_selected = True
                    break
                except Exception as click_error:
                    print(f"    ⚠️  Could not click date element: {click_error}")
                    continue
                    
            except Exception as e:
                print(f"    ⚠️  Error processing date element: {e}")
                continue

        if not date_selected:
            # Final fallback: try to click any radio button or clickable element
            all_clickable = driver.find_elements(By.XPATH, '//input[@type="radio"] | //button[not(@disabled)]')
            for element in all_clickable[:5]:  # Try first 5 elements
                try:
                    driver.execute_script("arguments[0].click();", element)
                    print("    📅 Selected first available option")
                    date_selected = True
                    break
                except:
                    continue
                    
        if not date_selected:
            raise Exception(
                f"No available dates found. Found {len(date_elements)} date elements but none were selectable. "
                f"The page layout may have changed or no dates are available."
            )

        # STEP 5: Select a timeslot
        print("  Step 5: Selecting a free timeslot...")
        time.sleep(2)  # Wait for timeslots to load after date selection

        # Look for timeslot elements
        timeslot_elements = []
        
        # Try to find radio buttons for timeslots
        timeslot_radios = driver.find_elements(By.XPATH, '//input[@type="radio" and (contains(@name, "time") or contains(@aria-label, "time") or contains(@aria-label, "slot"))]')
        if timeslot_radios:
            print(f"    Found {len(timeslot_radios)} timeslot radio buttons")
            timeslot_elements = timeslot_radios
        
        # Try to find clickable timeslot buttons
        if not timeslot_elements:
            timeslot_buttons = driver.find_elements(By.XPATH, '//button[contains(@aria-label, "time") or contains(text(), "AM") or contains(text(), "PM") or contains(text(), ":")]')
            if timeslot_buttons:
                print(f"    Found {len(timeslot_buttons)} timeslot buttons")
                timeslot_elements = timeslot_buttons
        
        # Try to find any elements with timeslot-related data attributes
        if not timeslot_elements:
            timeslot_elements = driver.find_elements(By.CSS_SELECTOR, '[data-testid*="time"], [data-qe-id*="time"], [aria-label*="time"], [class*="time"]')
            if timeslot_elements:
                print(f"    Found {len(timeslot_elements)} time-related elements")

        timeslot_selected = False
        for element in timeslot_elements:
            try:
                element_text = element.get_attribute('textContent') or element.text or ''
                aria_label = element.get_attribute('aria-label') or ''
                combined_text = f"{element_text} {aria_label}".lower()
                
                # Skip if disabled or full
                if element.get_attribute('disabled') or 'full' in combined_text or 'unavailable' in combined_text:
                    continue
                
                # Look for free timeslots or ones with pricing
                if 'free' in combined_text or '$0' in combined_text or ('am' in combined_text or 'pm' in combined_text):
                    try:
                        if element.tag_name == 'input':
                            driver.execute_script("arguments[0].click();", element)
                        else:
                            element.click()
                        
                        print(f"    🕐 Selected timeslot: {element_text or aria_label}")
                        human_like_delay()
                        timeslot_selected = True
                        break
                    except Exception as click_error:
                        print(f"    ⚠️  Could not click timeslot: {click_error}")
                        continue
                        
            except Exception as e:
                continue

        if not timeslot_selected:
            # Fallback: try any available radio button or clickable element
            remaining_clickable = driver.find_elements(By.XPATH, '//input[@type="radio"][not(@disabled)] | //button[not(@disabled)]')
            for element in remaining_clickable[:5]:
                try:
                    driver.execute_script("arguments[0].click();", element)
                    print("    🕐 Selected first available timeslot")
                    timeslot_selected = True
                    break
                except:
                    continue

        if not timeslot_selected:
            raise Exception(
                f"No free timeslots found. Found {len(timeslot_elements)} timeslot elements but none were selectable. "
                f"The page layout may have changed or no timeslots are available."
            )

        # STEP 6: Click confirmation button
        print("  Step 6: Clicking confirmation button...")
        
        confirm_selectors = [
            '//button[contains(text(), "Select this time")]',
            '//button[contains(text(), "Confirm")]',
            '//button[contains(text(), "Save")]',
            '//button[contains(text(), "Schedule")]',
            '//button[contains(@aria-label, "confirm")]',
            '//button[contains(@data-qe-id, "fulfill")]',
            '//button[contains(@data-qe-id, "schedule")]',
            '//button[contains(@data-qe-id, "save")]'
        ]
        
        confirm_button = None
        for selector in confirm_selectors:
            try:
                confirm_button = wait.until(EC.element_to_be_clickable((By.XPATH, selector)))
                break
            except:
                continue
        
        if confirm_button:
            try:
                confirm_button.click()
                print("    ✓ Clicked confirmation button")
            except:
                driver.execute_script("arguments[0].click();", confirm_button)
                print("    ✓ Clicked confirmation button (JS)")
        else:
            # Look for any prominent button that might be the confirmation
            all_buttons = driver.find_elements(By.TAG_NAME, 'button')
            for button in all_buttons:
                if not button.get_attribute('disabled'):
                    button_text = (button.text or '').lower()
                    if any(word in button_text for word in ['select', 'confirm', 'save', 'continue', 'next']):
                        try:
                            button.click()
                            print(f"    ✓ Clicked button: {button.text}")
                            break
                        except:
                            continue
            else:
                print("    ⚠️  Could not find confirmation button, proceeding anyway")

        print("  ✓ Time slot reservation process completed!")
        random_time()

        # Wait for any modal to close or page to update
        time.sleep(3)

        # Try to close any remaining modal
        try:
            close_elements = driver.find_elements(By.XPATH, '//button[contains(@aria-label, "close") or contains(@aria-label, "Close") or contains(text(), "×")]')
            for close_elem in close_elements:
                try:
                    close_elem.click()
                    print("  ✓ Closed modal")
                    break
                except:
                    continue
        except:
            print("  ℹ️  No modal to close or already closed")

        return True

    except Exception as e:
        logger.log_failure(
            driver=driver,
            function_name="reserve_time_slot",
            error=e,
            additional_info={
                "step": "reserving time slot",
                "url": driver.current_url
            }
        )
        # Try to close modal on failure
        try:
            close_buttons = driver.find_elements(By.XPATH, '//button[contains(@aria-label, "close") or contains(text(), "×")]')
            for btn in close_buttons:
                try:
                    btn.click()
                    break
                except:
                    continue
        except:
            pass
        raise
