"""
Self-Healing Function Module

Uses Claude to analyze runtime errors and rewrite broken functions on the fly.
Rewritten functions are saved to updated_functions/ for later review and permanent application.
"""
import os
import re
import base64
import inspect
import textwrap
import traceback
import datetime
import time
from claude import client


# Directory to save rewritten functions
UPDATED_FUNCTIONS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "updated_functions")


def _ensure_output_dir():
    """Create the updated_functions directory if it doesn't exist."""
    os.makedirs(UPDATED_FUNCTIONS_DIR, exist_ok=True)


def _save_updated_function(func_name, new_code, source_file, attempt, error_msg):
    """
    Save a rewritten function to updated_functions/<func_name>.py

    If the file already exists, it is overwritten with the latest version.
    A header comment records metadata about the rewrite.
    """
    _ensure_output_dir()

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = (
        f"# Auto-generated by self_healing on {timestamp}\n"
        f"# Original function: {func_name}\n"
        f"# Source file: {source_file}\n"
        f"# Healing attempt: {attempt}\n"
        f"# Error that triggered rewrite: {error_msg}\n"
        f"#\n"
        f"# Review this code before applying with apply_updates.py\n\n"
    )

    filepath = os.path.join(UPDATED_FUNCTIONS_DIR, f"{func_name}.py")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(new_code)
        f.write("\n")

    print(f"    💾 Saved rewritten function to: updated_functions/{func_name}.py")
    return filepath


def _extract_function_code(response_text):
    """
    Extract Python function code from Claude's response.
    Strips markdown fences if present.
    """
    # Remove markdown code fences
    cleaned = re.sub(r"^```(?:python)?\s*\n", "", response_text.strip())
    cleaned = re.sub(r"\n```\s*$", "", cleaned)
    return cleaned.strip()


def _capture_screenshot_b64(driver):
    """Capture a screenshot from the Selenium driver as a base64 string."""
    try:
        return driver.get_screenshot_as_base64()
    except Exception as e:
        print(f"    ⚠️  Could not capture screenshot: {e}")
        return None


def _build_heal_prompt(func_name, source, error, tb_str, html_context=None):
    """Build the text prompt sent to Claude for function repair."""
    prompt = (
        f"The following Python function raised an error at runtime.\n\n"
        f"Function name: {func_name}\n"
        f"Error type: {type(error).__name__}\n"
        f"Error message: {error}\n\n"
        f"Traceback:\n{tb_str}\n\n"
        f"Current function source:\n```python\n{source}\n```\n\n"
    )

    if html_context:
        # Truncate HTML to avoid exceeding context limits
        max_html = 50000
        if len(html_context) > max_html:
            html_context = html_context[:max_html] + "\n... (truncated)"
        prompt += (
            f"Here is the HTML of the page at the time of the error "
            f"(use this to find correct selectors):\n"
            f"```html\n{html_context}\n```\n\n"
        )

    prompt += (
        "A screenshot of the browser at the time of the error is attached. "
        "Use it to understand what the user is seeing and what elements are visible.\n\n"
        "Please rewrite ONLY this function to fix the error. "
        "Keep the same function name and signature. "
        "Return ONLY the corrected Python function code with no markdown fences, "
        "no explanation, and no imports (assume all original imports are available)."
    )
    return prompt


def _build_message_content(prompt_text, screenshot_b64=None):
    """Build the message content list with text and optional image."""
    content = []

    if screenshot_b64:
        content.append({
            "type": "image",
            "source": {
                "type": "base64",
                "media_type": "image/png",
                "data": screenshot_b64,
            },
        })

    content.append({
        "type": "text",
        "text": prompt_text,
    })

    return content


def dismiss_modals(driver):
    """Dismiss any modal overlays that may be blocking interaction.
    
    Tries multiple strategies to close popups/modals that HEB shows
    (delivery fee promos, cookie consent, etc.). Runs silently — 
    only prints when it actually closes something.
    """
    from selenium.webdriver.common.by import By

    closed_any = False

    # Strategy 1: Click modal close buttons (X icons)
    close_selectors = [
        '[data-qe-id="modalClose"]',
        'button[aria-label="Close"]',
        'button[aria-label="close"]',
        '.modal-close',
        '[data-component="modal-cover-container"] ~ div button',
    ]
    for selector in close_selectors:
        try:
            buttons = driver.find_elements(By.CSS_SELECTOR, selector)
            for btn in buttons:
                if btn.is_displayed():
                    driver.execute_script("arguments[0].click();", btn)
                    time.sleep(0.5)
                    closed_any = True
        except Exception:
            pass

    # Strategy 2: Click the X button by common SVG close icon patterns
    try:
        close_buttons = driver.find_elements(
            By.XPATH,
            '//button[contains(@class, "close") or contains(@class, "Close")]'
        )
        for btn in close_buttons:
            if btn.is_displayed():
                driver.execute_script("arguments[0].click();", btn)
                time.sleep(0.5)
                closed_any = True
    except Exception:
        pass

    # Strategy 3: Remove modal overlay divs via JavaScript
    try:
        removed = driver.execute_script("""
            var covers = document.querySelectorAll('[data-component="modal-cover-container"]');
            var modals = document.querySelectorAll('[data-component="modal-container"]');
            var count = 0;
            covers.forEach(function(el) { el.remove(); count++; });
            modals.forEach(function(el) { el.remove(); count++; });
            return count;
        """)
        if removed and removed > 0:
            closed_any = True
    except Exception:
        pass

    if closed_any:
        print("    \u2139\ufe0f  Dismissed blocking modal(s)")
        time.sleep(0.5)


def self_healing_call(func, *args, max_retries=3, html_context=None, driver=None, **kwargs):
    """
    Call a function with LLM-powered auto-repair on failure.

    On exception, sends the function source, error, optional HTML context,
    and a screenshot to Claude, which rewrites the function. The rewritten
    version is compiled via exec, saved to updated_functions/, and retried.

    Args:
        func: The function to call.
        *args: Positional arguments to pass to the function.
        max_retries: Maximum number of heal-and-retry attempts (default 3).
        html_context: Optional HTML string (e.g. page source) to help Claude
                      find correct selectors.
        driver: Optional Selenium WebDriver instance. If provided, a screenshot
                is captured at the time of error and sent to Claude's vision API.
        **kwargs: Keyword arguments to pass to the function.

    Returns:
        The return value of the function on success.

    Raises:
        The last exception if all retries are exhausted.
    """
    if client is None:
        raise RuntimeError(
            "Claude API client not initialized. "
            "Cannot use self-healing without a valid API key."
        )

    source = textwrap.dedent(inspect.getsource(func))
    source_file = inspect.getfile(func)
    current_func = func

    for attempt in range(max_retries + 1):
        try:
            return current_func(*args, **kwargs)
        except Exception as e:
            tb_str = traceback.format_exc()

            # If the browser connection is dead (e.g. after Ctrl+C killed
            # chromedriver), don't waste retries — bail immediately.
            if "Connection refused" in str(e) or "NewConnectionError" in str(e):
                print(
                    f"\n    ❌ {func.__name__}: Browser connection lost. "
                    f"Skipping retries."
                )
                raise

            # On the last attempt, don't try to heal — just raise
            if attempt == max_retries:
                print(
                    f"\n    ❌ self_healing: {func.__name__} failed after "
                    f"{max_retries} heal attempts. Raising original error."
                )
                raise

            print(
                f"\n    🔧 self_healing: {func.__name__} raised "
                f"{type(e).__name__}: {e}"
            )
            print(f"    🤖 Asking Claude to rewrite (attempt {attempt + 1}/{max_retries})...")

            # Capture screenshot at the moment of error
            screenshot_b64 = None
            if driver:
                print("    📸 Capturing screenshot for Claude...")
                screenshot_b64 = _capture_screenshot_b64(driver)

            # Get fresh HTML context from driver if not provided
            current_html = html_context
            if driver and not current_html:
                try:
                    current_html = driver.page_source
                except Exception:
                    pass

            # Build prompt and ask Claude
            prompt = _build_heal_prompt(
                func.__name__, source, e, tb_str, current_html
            )

            # Build message content (text + optional screenshot)
            message_content = _build_message_content(prompt, screenshot_b64)

            response = client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=4096,
                messages=[{"role": "user", "content": message_content}],
            )

            new_code = _extract_function_code(response.content[0].text)

            # Compile the new function in the original function's namespace
            namespace = {**func.__globals__}
            try:
                exec(new_code, namespace)
            except SyntaxError as se:
                print(f"    ⚠️  Claude returned code with syntax error: {se}")
                print(f"    Retrying with original function...")
                continue

            if func.__name__ not in namespace:
                print(
                    f"    ⚠️  Claude's response did not define {func.__name__}. "
                    f"Retrying with original function..."
                )
                continue

            current_func = namespace[func.__name__]
            source = new_code

            # Save the rewrite for later review
            _save_updated_function(
                func.__name__,
                new_code,
                source_file,
                attempt + 1,
                f"{type(e).__name__}: {e}",
            )

            print(f"    ⟳ Retrying with rewritten {func.__name__}...")
