"""
Apply Updated Functions (self-healing review tool)

Reads the Claude-rewritten functions that the nodriver self-healing layer
(``session_maintenance/self_healing.py``) saves to
``session_maintenance/updated_functions/`` and splices each one back into its
original source file (e.g. ``session_maintenance/flows.py``).

These rewrites are produced at runtime whenever a flow function breaks — both
locally and inside the Docker container (the compose file bind-mounts
``session_maintenance/updated_functions`` so in-container heals land in your working
tree). This script lets you review them and apply the good ones.

Usage:
    python scripts/apply_updates.py                # Preview all changes (dry run)
    python scripts/apply_updates.py --list         # List available updates
    python scripts/apply_updates.py --apply        # Apply all changes
    python scripts/apply_updates.py --apply login  # Apply only the 'login' function

After applying, review the diff and run the flow again before committing.
"""
import glob
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# The app now lives under src/auto_grocer/ (installable package layout).
_PKG_ROOT = os.path.join(REPO_ROOT, "src", "auto_grocer")
UPDATED_FUNCTIONS_DIR = os.path.join(_PKG_ROOT, "session_maintenance", "updated_functions")

# Where to look for a function when the recorded source path can't be used
# (e.g. it was captured inside Docker as /app/src/auto_grocer/session_maintenance/flows.py).
_SEARCH_GLOBS = (
    os.path.join(_PKG_ROOT, "session_maintenance", "*.py"),
    os.path.join(_PKG_ROOT, "utility", "*.py"),
)


def parse_update_header(filepath):
    """
    Parse the header comments from an updated function file.

    Returns a dict with keys: func_name, source_file, attempt, error, timestamp.
    """
    info = {}
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            if not line.startswith("#"):
                break
            if "Original function:" in line:
                info["func_name"] = line.split(":", 1)[1].strip()
            elif "Source file:" in line:
                info["source_file"] = line.split(":", 1)[1].strip()
            elif "Healing attempt:" in line:
                info["attempt"] = line.split(":", 1)[1].strip()
            elif "Error that triggered rewrite:" in line:
                info["error"] = line.split(":", 1)[1].strip()
            elif "self_healing on" in line:
                # "# Auto-generated by [nodriver] self_healing on <timestamp>"
                info["timestamp"] = line.split(" on ", 1)[-1].strip()
    return info


def read_function_body(filepath):
    """
    Read the function code from an updated function file, skipping header comments.
    """
    lines = []
    past_header = False
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            if not past_header:
                if line.startswith("#") or line.strip() == "":
                    continue
                past_header = True
            lines.append(line)

    # Strip trailing blank lines
    while lines and lines[-1].strip() == "":
        lines.pop()

    return "".join(lines)


def find_function_in_source(source_code, func_name):
    """
    Find the start and end positions of a function definition in source code.

    Handles both ``def`` and ``async def``. Returns (start_index, end_index) or
    None if not found.
    """
    # Match 'def func_name(' or 'async def func_name(' at the start of a line
    # (with possible indentation).
    pattern = re.compile(
        rf"^([ \t]*)(?:async\s+)?def\s+{re.escape(func_name)}\s*\(",
        re.MULTILINE,
    )

    match = pattern.search(source_code)
    if not match:
        return None

    start = match.start()
    indent = match.group(1)
    indent_len = len(indent)

    # Find the end of the function: next line at the same or lesser indentation
    # that isn't blank, a comment, or a decorator.
    lines = source_code[start:].split("\n")
    end_offset = 0

    for i, line in enumerate(lines):
        if i == 0:
            end_offset += len(line) + 1  # +1 for newline
            continue

        stripped = line.rstrip()

        # Blank lines or comments inside the function body
        if stripped == "" or stripped.lstrip().startswith("#"):
            end_offset += len(line) + 1
            continue

        # Check indentation: if this line has <= the function def indentation
        # and is actual code, the function has ended.
        line_indent = len(line) - len(line.lstrip())
        if line_indent <= indent_len and stripped:
            break

        end_offset += len(line) + 1

    end = start + end_offset

    return start, end


def _candidate_source_paths(recorded_path):
    """Yield possible host paths for a recorded (possibly container) source path.

    The header's ``Source file`` comes from ``inspect.getfile`` and may be an
    absolute path captured inside Docker (e.g. ``/app/session_maintenance/flows.py``)
    that does not exist on the host. Re-root anything under a known package
    directory back into this repo.
    """
    if not recorded_path:
        return
    yield recorded_path
    norm = recorded_path.replace("\\", "/")
    for seg in ("session_maintenance/", "utility/"):
        idx = norm.find(seg)
        if idx != -1:
            yield os.path.join(_PKG_ROOT, *norm[idx:].split("/"))
    # Last resort: same basename under session_maintenance/.
    yield os.path.join(_PKG_ROOT, "session_maintenance", os.path.basename(norm))


def resolve_source_file(recorded_path, func_name):
    """Find the real host file that actually contains ``func_name``."""
    seen = set()
    for cand in _candidate_source_paths(recorded_path):
        if not cand or cand in seen:
            continue
        seen.add(cand)
        if os.path.exists(cand):
            with open(cand, "r", encoding="utf-8") as f:
                if find_function_in_source(f.read(), func_name):
                    return cand

    # Fallback: scan known package dirs for the function definition.
    for pattern in _SEARCH_GLOBS:
        for cand in sorted(glob.glob(pattern)):
            with open(cand, "r", encoding="utf-8") as f:
                if find_function_in_source(f.read(), func_name):
                    return cand
    return None


def list_updates():
    """List all available function updates."""
    if not os.path.exists(UPDATED_FUNCTIONS_DIR):
        print("No session_maintenance/updated_functions/ directory found.")
        return []

    updates = []
    for filename in sorted(os.listdir(UPDATED_FUNCTIONS_DIR)):
        if not filename.endswith(".py"):
            continue

        filepath = os.path.join(UPDATED_FUNCTIONS_DIR, filename)
        info = parse_update_header(filepath)
        updates.append((filename, info))

    return updates


def preview_update(filepath, info):
    """Show a diff-like preview of what would change."""
    func_name = info.get("func_name", "unknown")
    source_file = resolve_source_file(info.get("source_file", ""), func_name)

    if not source_file:
        print(f"  ⚠️  Could not locate a host file containing '{func_name}'")
        return False

    with open(source_file, "r", encoding="utf-8") as f:
        source_code = f.read()

    bounds = find_function_in_source(source_code, func_name)
    if not bounds:
        print(f"  ⚠️  Could not find function '{func_name}' in {source_file}")
        return False

    start, end = bounds
    old_code = source_code[start:end].rstrip()
    new_code = read_function_body(filepath).rstrip()

    rel = os.path.relpath(source_file, REPO_ROOT)
    print(f"\n  📄 Source file: {rel}")
    print(f"  🔧 Function: {func_name}")
    print(f"  📅 Rewritten: {info.get('timestamp', 'unknown')}")
    print(f"  ❌ Error: {info.get('error', 'unknown')}")
    print(f"\n  --- OLD ({len(old_code.splitlines())} lines) ---")
    for line in old_code.splitlines()[:5]:
        print(f"  - {line}")
    if len(old_code.splitlines()) > 5:
        print(f"  ... ({len(old_code.splitlines()) - 5} more lines)")
    print(f"\n  +++ NEW ({len(new_code.splitlines())} lines) ---")
    for line in new_code.splitlines()[:5]:
        print(f"  + {line}")
    if len(new_code.splitlines()) > 5:
        print(f"  ... ({len(new_code.splitlines()) - 5} more lines)")

    return True


def apply_update(filepath, info):
    """Replace the function in the original source file with the updated version."""
    func_name = info.get("func_name", "unknown")
    source_file = resolve_source_file(info.get("source_file", ""), func_name)

    if not source_file:
        print(f"  ❌ Could not locate a host file containing '{func_name}'")
        return False

    with open(source_file, "r", encoding="utf-8") as f:
        source_code = f.read()

    bounds = find_function_in_source(source_code, func_name)
    if not bounds:
        print(f"  ❌ Could not locate function '{func_name}' in {source_file}")
        return False

    start, end = bounds
    new_code = read_function_body(filepath)

    # Preserve the original indentation
    old_func = source_code[start:end]
    original_indent = ""
    for ch in old_func:
        if ch in (" ", "\t"):
            original_indent += ch
        else:
            break

    # Indent the new code to match the original if needed
    if original_indent:
        new_lines = new_code.splitlines(True)
        indented = []
        for i, line in enumerate(new_lines):
            if i == 0:
                indented.append(original_indent + line.lstrip())
            elif line.strip():
                indented.append(original_indent + line)
            else:
                indented.append(line)
        new_code = "".join(indented)

    # Replace in source
    updated_source = source_code[:start] + new_code + "\n" + source_code[end:]

    with open(source_file, "w", encoding="utf-8") as f:
        f.write(updated_source)

    rel = os.path.relpath(source_file, REPO_ROOT)
    print(f"  ✅ Applied '{func_name}' update to {rel}")
    return True


def main():
    args = sys.argv[1:]

    if not args:
        # Default: dry-run preview
        args = ["--preview"]

    command = args[0]
    filter_names = args[1:] if len(args) > 1 else []

    updates = list_updates()

    if not updates:
        print("No function updates found in session_maintenance/updated_functions/")
        return

    if command == "--list":
        print(f"\n📋 Available function updates ({len(updates)}):\n")
        for filename, info in updates:
            resolved = resolve_source_file(info.get("source_file", ""), info.get("func_name", ""))
            status = "✓" if resolved else "⚠️"
            print(f"  {status} {info.get('func_name', filename)}")
            print(f"    Source: {os.path.relpath(resolved, REPO_ROOT) if resolved else info.get('source_file', 'unknown')}")
            print(f"    Error:  {info.get('error', 'unknown')}")
            print(f"    Time:   {info.get('timestamp', 'unknown')}")
            print()

    elif command == "--preview":
        print(f"\n🔍 Previewing {len(updates)} update(s) (dry run):\n")
        for filename, info in updates:
            func_name = info.get("func_name", "")
            if filter_names and func_name not in filter_names:
                continue
            filepath = os.path.join(UPDATED_FUNCTIONS_DIR, filename)
            preview_update(filepath, info)
            print()

    elif command == "--apply":
        print("\n🔧 Applying function updates:\n")
        applied = 0
        failed = 0
        for filename, info in updates:
            func_name = info.get("func_name", "")
            if filter_names and func_name not in filter_names:
                continue
            filepath = os.path.join(UPDATED_FUNCTIONS_DIR, filename)
            if apply_update(filepath, info):
                applied += 1
            else:
                failed += 1

        print(f"\n📊 Results: {applied} applied, {failed} failed")
        if applied > 0:
            print("💡 Review the changes and test before committing.")

    else:
        print(f"Unknown command: {command}")
        print("Usage:")
        print("  python scripts/apply_updates.py              # Preview changes (dry run)")
        print("  python scripts/apply_updates.py --list       # List available updates")
        print("  python scripts/apply_updates.py --apply      # Apply all updates")
        print("  python scripts/apply_updates.py --apply NAME # Apply specific function")


if __name__ == "__main__":
    main()
