# Auto-generated by nodriver self_healing on 2026-08-11 21:36:21
# Original function: change_store_via_ui
# Source file: /app/session_maintenance/flows.py
# Healing attempt: 3
# Error that triggered rewrite: Exception: Could not find a dedicated store-search input.
# NOTE: async nodriver function. Review before applying.

async def change_store_via_ui(tab, search_text):
    """Exercise HEB's store-change UI (StoreSearch + SelectPickupFulfillment)."""
    print("  Step 1: Opening the store/fulfillment selector...")
    await tab.get(HEB_HOME)
    await random_time()

    opener = None
    opened = False
    
    # Look for the visible store/fulfillment button in the header
    # From the screenshot, there's a button showing "Curbside at Kyle H-E-B plus!"
    for selector in [
        'button:has-text("Curbside at")',
        'button:has-text("Kyle H-E-B")',
        'header button[class*="store"]',
        'header button[aria-label*="store"]',
        'button[class*="storeSelection"]',
    ]:
        try:
            elements = await tab.select_all(selector, timeout=2)
            for el in elements:
                if await is_visible(el):
                    opener = el
                    break
            if opener:
                await click_element(tab, opener)
                opened = True
                print(f"    ✓ Opened selector via {selector}")
                break
        except:
            continue
    
    if not opened:
        # Try XPath patterns
        for xp in [
            '//button[contains(text(), "Curbside at")]',
            '//button[contains(text(), "Kyle H-E-B")]',
            '//header//button[contains(@class, "store")]',
        ]:
            results = await tab.xpath(xp, timeout=2)
            for el in results:
                if await is_visible(el):
                    opener = el
                    await click_element(tab, opener)
                    opened = True
                    print(f"    ✓ Opened selector via {xp}")
                    break
            if opened:
                break
    
    if not opened:
        raise Exception("Could not find the store/fulfillment selector button.")
    
    await random_time()

    # Optional "change store" affordance.
    for xp in [
        '//button[contains(., "Change store") or contains(., "Change my store")]',
        '//a[contains(., "Change store")]',
        '//button[contains(., "Find a store") or contains(., "store near")]',
    ]:
        results = await tab.xpath(xp, timeout=2)
        for el in results:
            if await is_visible(el):
                await click_element(tab, el)
                print(f"    ✓ Clicked change-store via {xp}")
                await random_time()
                break

    print("  Step 3: Searching stores by location...")
    await asyncio.sleep(1)
    search_input = None
    for xp in [
        '//div[@role="dialog"]//input[@type="text"]',
        '//div[@role="dialog"]//input[@placeholder]',
        '//input[contains(@placeholder, "address")]',
        '//input[contains(@placeholder, "zip")]',
        '//input[contains(@placeholder, "city")]',
        '//input[@type="text"]',
        '//input[@type="search"]',
    ]:
        results = await tab.xpath(xp, timeout=2)
        for el in results:
            if await is_visible(el):
                search_input = el
                print(f"    ✓ Found store search input via {xp}")
                break
        if search_input:
            break
    
    if search_input is None:
        # Try CSS selectors as fallback
        for selector in [
            'input[type="text"]',
            'input[type="search"]',
            'input[placeholder]',
        ]:
            try:
                elements = await tab.select_all(selector, timeout=2)
                for el in elements:
                    if await is_visible(el):
                        search_input = el
                        print(f"    ✓ Found store search input via {selector}")
                        break
                if search_input:
                    break
            except:
                continue
    
    if search_input is None:
        raise Exception("Could not find a dedicated store-search input.")

    await human_like_typing(search_input, str(search_text))
    await asyncio.sleep(0.8)
    await search_input.send_keys("\r")
    await random_time()
    await random_time()

    print("  Step 4: Selecting the first store result...")
    for xp in [
        '//button[contains(., "Selected Store")]',
        '//button[contains(., "Select Store")]',
        '//button[contains(., "Make my store") or contains(., "Select") or contains(., "Shop this store")]',
        '//button[contains(@aria-label, "Select") and contains(@aria-label, "store")]',
    ]:
        results = await tab.xpath(xp, timeout=2)
        for el in results:
            if await is_visible(el):
                await click_element(tab, el)
                print(f"    ✓ Selected a store via {xp}")
                await random_time()
                return True

    sel_btn = await select_one(tab, '[data-qe-id="selectStoreButton"]', timeout=2)
    if sel_btn:
        await click_element(tab, sel_btn)
        await random_time()
        return True

    print("    ⚠️  Could not click a store-select button; StoreSearch may still be captured.")
    return True
