# Auto-generated by nodriver self_healing on 2026-07-15 18:58:13
# Original function: change_store_via_ui
# Source file: /app/session_maintenance/flows.py
# Healing attempt: 3
# Error that triggered rewrite: Exception: Could not find the store/fulfillment selector button.
# NOTE: async nodriver function. Review before applying.

async def change_store_via_ui(tab, search_text):
    """Exercise HEB's store-change UI (StoreSearch + SelectPickupFulfillment)."""
    print("  Step 1: Opening the store/fulfillment selector...")
    await tab.get(HEB_HOME)
    await random_time()

    # Try to find and click the fulfillment button in the header
    opener = None
    opened = False
    
    # Look for the fulfillment button that shows store info - in the HTML it's a button with store icon
    for selector in [
        'button[aria-label*="Kyle"]',
        'button[aria-label*="Curbside"]',
        'button[aria-label*="store"]',
        'header button:has-text("Kyle")',
        'header a[href*="store"]',
        'button:has([data-testid="fulfillment-icon"])',
        '[data-testid="fulfillment-button"]',
        'header button'
    ]:
        try:
            elements = await tab.select_all(selector, timeout=2)
            for el in elements:
                if await is_visible(el):
                    # Check if this element contains store-related text
                    text_content = await el.apply('(e) => e.textContent || ""')
                    aria_label = el.attrs.get('aria-label', '')
                    if 'Kyle' in text_content or 'Kyle' in aria_label or 'Curbside' in text_content or 'Curbside' in aria_label:
                        await click_element(tab, el)
                        opened = True
                        print(f"    ✓ Opened selector via {selector}")
                        break
            if opened:
                break
        except:
            continue
    
    # If CSS selectors didn't work, try XPath to find clickable element with store info
    if not opened:
        for xp in [
            '//button[contains(@aria-label, "Kyle")]',
            '//button[contains(@aria-label, "Curbside")]',
            '//button[contains(@aria-label, "store")]',
            '//header//button[contains(., "Kyle")]',
            '//header//a[contains(., "Kyle")]',
            '//button[contains(., "Kyle H-E-B")]',
            '//a[contains(., "Kyle H-E-B")]',
            '//header//button[.//*[name()="svg"]]'
        ]:
            if await _click_first_xpath(tab, xp):
                opened = True
                print(f"    ✓ Opened selector via {xp}")
                break
    
    if not opened:
        raise Exception("Could not find the store/fulfillment selector button.")
    
    await random_time()

    # Optional "change store" affordance.
    for xp in [
        '//button[contains(., "Change store") or contains(., "Change my store")]',
        '//a[contains(., "Change store")]',
        '//button[contains(., "Find a store") or contains(., "store near")]',
    ]:
        if await _click_first_xpath(tab, xp):
            print(f"    ✓ Clicked change-store via {xp}")
            await random_time()
            break

    print("  Step 3: Searching stores by location...")
    await asyncio.sleep(1)
    search_input = None
    for xp in [
        '//div[@role="dialog"]//input[@type="text"]',
        '//div[@role="dialog"]//input[@placeholder]',
        '//input[contains(@placeholder, "address")]',
        '//input[contains(@placeholder, "zip")]',
        '//input[contains(@placeholder, "city")]',
    ]:
        for el in await xpath_all(tab, xp):
            if await is_visible(el):
                search_input = el
                print(f"    ✓ Found store search input via {xp}")
                break
        if search_input:
            break
    if search_input is None:
        raise Exception("Could not find a dedicated store-search input.")

    await human_like_typing(search_input, str(search_text))
    await asyncio.sleep(0.8)
    await search_input.send_keys("\r")
    await random_time()
    await random_time()

    print("  Step 4: Selecting the first store result...")
    for xp in [
        '//button[contains(., "Selected Store")]',
        '//button[contains(., "Select Store")]',
        '//button[contains(., "Make my store") or contains(., "Select") or contains(., "Shop this store")]',
        '//button[contains(@aria-label, "Select") and contains(@aria-label, "store")]',
    ]:
        if await _click_first_xpath(tab, xp):
            print(f"    ✓ Selected a store via {xp}")
            await random_time()
            return True

    sel_btn = await select_one(tab, '[data-qe-id="selectStoreButton"]', timeout=2)
    if sel_btn:
        await click_element(tab, sel_btn)
        await random_time()
        return True

    print("    ⚠️  Could not click a store-select button; StoreSearch may still be captured.")
    return True
